version: '3'

volumes:
  mongo_db:


services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  nginx:
    build: ./nginx/
    ports:
      - 8000:80
    depends_on:
      - app
  app:
    build: ./app/
    depends_on:
      - db
